defaults: &defaults
  adapter: mysql2
  encoding: utf8
  reconnect: false
  #port: 4001
  pool: 5
  username: remindamail
  password: seivanheidari
  host: localhost

  
development: &development
  <<: *defaults
  database: remindamail_development

production: &production
  <<: *defaults
  database: remindamail_production

test: &test
  <<: *defaults
  database: remindamail_test
