# MySQL.  Versions 4.1 and 5.0 are recommended.
#
# Install the MySQL driver:
#   gem install mysql2
#
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html
defaults: &defaults
  adapter: mysql2
  encoding: utf8
  reconnect: false
  #host:
  #port: 4001
  pool: 5
  username: root
  password: seivanheidari
  host: localhost
  
development: &development
  <<: *defaults
  database: remindamail_development

production: &production
  <<: *defaults
  database: remindamail_production

test: &test
  <<: *defaults
  database: remindamail_test
